name: fraud-file-to-landing-parquet
project_id: case-grupo-otg
region: southamerica-east1
artifact_registry_repository: fraud-jobs
image_name: fraud-file-to-landing-parquet
memory: 512Mi
cpu: "1"
max_retries: "1"
tasks: "1"
timeout: 900s
service_account: cloud-run-jobs@case-grupo-otg.iam.gserviceaccount.com
env:
  GCP_PROJECT_ID: case-grupo-otg
